[phases.setup]

[phases.install]
cmds = ["cd ITEC275LiveQuiz && dotnet restore"]

[phases.build]
cmds = ["cd ITEC275LiveQuiz && dotnet publish -c Release -o ../out"]

[start]
cmd = "dotnet out/ITEC275LiveQuiz.dll"
