[phases.setup]
nixPkgs = ['dotnet-sdk_10']

[phases.build]
cmds = [
  'dotnet --version',
  'dotnet publish ITEC275LiveQuiz/ITEC275LiveQuiz.csproj -c Release -o out --framework net10.0'
]

[start]
cmd = 'cd out && ./ITEC275LiveQuiz'
