[build]
builder = "NIXPACKS"
buildCommand = "cd ITEC275LiveQuiz && dotnet restore && dotnet publish -c Release -o ../out"

[deploy]
startCommand = "dotnet out/ITEC275LiveQuiz.dll"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
